baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Coding Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "even"

publishDir = "../racingicemen.github.io"
hasCJKLanguage = true
paginate = 9 
disqusShortname = "racingicemen"      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name

[author]                  # essential          
  name = "Rajesh Kommu"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  version = "3.x"

  since = "2018"            # Site creation time

  # site info (optional)
  logoTitle = "Racing Icemen"        # default: the title value
  # keywords = ["Hugo", "theme","even"]
  description = "Annotated description of different software projects."

  # paginate of archives, tags and categories
  archivePaginate = 12

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006\u25e6Jan\u25e602\u25e6Mon"

  # show word count and read time ?
  moreMeta = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true 
  autoCollapseToc = false   # Auto expand and collapse toc
  fancybox = true           # see https://github.com/fancyapps/fancybo
  mathjax = true           # see https://www.mathjax.org/
  mathjaxEnableSingleDollar = false

  postMetaInFooter = true   # contain author, lastMod, markdown link, license
  linkToMarkDown = true    # Only effective when hugo will output .md files.
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.publicCDN]        # load these files from public cdn
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
  
  [params.social]
    a-email = "mailto:rajesh.kommu@gmail.com"
    b-stack-overflow = "https://stackoverflow.com/users/655345/rkk"
    c-twitter = "https://twitter.com/racingicemen"
    d-linkedin = "https://www.linkedin.com/in/rajesh-kommu-a276a698/"
    e-github = "https://github.com/racingicemen"
    # k-pocket = "https://getpocket.com/a/queue/"

[mediaTypes]
  [mediaTypes."text/plain"]
    suffix = "md"

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
